### ISSUE TITLE
adjustments and environment for working with this project

### ISSUE THREAD

**Issue by Jahn-KSB** [aldente0630/musinsaigo#1]
Hi, I saw your repo it looks very clean! :D nice work.
I would like to use it on AWS aswell but I don't know how you use it since there seems to be no documentation about the setup.
I run the main.py script on an EC2 instance and and run into some errors since I am in eu.
There has to be some adjustments regarding the docker containers you are using if someone wants to use it from different region. The config should be used in Dockerfile aswell.

https://github.com/aldente0630/musinsaigo/blob/main/containers/data_prep/Dockerfile#L1
https://github.com/aldente0630/musinsaigo/blob/main/containers/model_train/Dockerfile#L1

then here there is a typo:
https://github.com/aldente0630/musinsaigo/blob/main/containers/model_train/Dockerfile#L27
its configs. not config 👯 

some informations regarding the docker containers :
when build both are ≈ 11 GB and require  more than 25 gb storage. I had only 22 Gb free and run into a storage problem.

maybe you could give me more information about how you run it. Are you running the script from ec2? or SageMaker?
where are you using the lifecycle script? 

Best Regard
Jahn

**Comment by bits-bytes-nn** [comment]
Hi Jahn, thanks for the question and information. I have modified the code as you mentioned. I will let you know if the test completes successfully and close this issue.

For your information, I tried running the code in my local environment (Macbook), I set up my AWS credentials and Conda environment, and then installed all the packages in the requirements.txt. Of course, everything is running through SageMaker containers. 

I hope this helps.
